<?php
namespace App\Libraries;


class DropdownLib extends \App\Libraries\Sys\DropdownLib{
	/*
	ARRAY OF DROPDOWN VALUES
	*/
	
	public $values = array(
		'ativo_inativo_list' => array(
			'ativo' => 'Ativo',
			'inativo' => 'Inativo',
		),
		'status_inscrito' => array(
			'inscrito' => 'Inscrito',
			'cancelado' => 'Cancelado',
			'aprovado' => 'Aprovado/Presente',
			'reprovado' => 'Reprovado',
			'falta_just' => 'Falta Justificada',
			'nao_acessou' => 'Não Acessou/Faltou',		
		),
		'sim_nao' => array(
			'sim' => 'Sim',
			'nao' => 'Não',		
		),
		'tipo_acesso' => array(
			'public' => 'Público',
			'privado' => 'Privado',		
			'admin' => 'Apenas Admin',		
		),
		'fisica_juridica' => array(
			'pf' => 'Pessoa Física',
			'pj' => 'Pessoa Jurídica',		
		),
		'regime_tributacao' => array(
			'1' => 'Lucro Presumido',
			'2' => 'Lucro Real',		
			'3' => 'Lucro Arbitrado',		
			'5' => 'Outros',		
		),
		'origem' => array(
			'1' => 'Indicação',
			'2' => 'Internet',		
			'3' => 'Instituiçao de Ensino',		
			'4' => 'Mala Direta',		
			'5' => 'Outro',		
		),
		'tipo_usuario' => array(
			'admin' => 'Administrador',
			'colab' => 'Colaborador',
			'aluno' => 'Aluno',
		),
		'tipo_participante' => array(
			'cliente' => 'Cliente',
			'nao_cliente' => 'Visitante',
		),
		'sexo' => array(
			'm' => 'Masculino',
			'f' => 'Feminino',
		),
		'reside_em' => array(
			'1' => 'Casa',
			'2' => 'Apartamento',
		),
		'cursos_tipo' => array(
			'online' => 'Online',
			'zoom' => 'Online Zoom',
			'presencial' => 'Presencial',
			'videoaula' => 'Videoaula',
			'youtube' => 'YouTube',
			'hibrido' => 'Híbrido (Não Utilizar)',
		),
		'cursos_tipo_front' => array(
			'online' => 'Online',
			'presencial' => 'Presencial',
		),
		'apostilas_tipo' => array(
			'apostila' => 'Apostila',
			'manual' => 'Manual',
		),
		'area_atuacao' => array(
			"1" => "Área Contábil",
			"2" => "Área Trabalhista",
			"3" => "Área Tributária",
			"4" => "Outros Cursos",
		),
		'semana_sabado' => array(
			"1" => "Durante a semana",
			"2" => "Aos Sábado",
		),
		'periodo_list' => array(
			"1" => "Manhã",
			"2" => "Tarde",
			"3" => "Noite",
			"4" => "Integral",
		),
		'periodo_indiferente_list' => array(
			"1" => "Manhã",
			"2" => "Tarde",
			"3" => "Noite",
			"4" => "Integral",
			"5" => "Indiferente",
		),
		'tipo_rua' => array(
			"Aeroporto" => "Aeroporto",
			"Alameda" => "Alameda",
			"Área" => "Área",
			"Avenida" => "Avenida",
			"Campo" => "Campo",
			"Chácara" => "Chácara",
			"Colônia" => "Colônia",
			"Condomínio" => "Condomínio",
			"Conjunto" => "Conjunto",
			"Distrito" => "Distrito",
			"Esplanada" => "Esplanada",
			"Estação" => "Estação",
			"Estrada" => "Estrada",
			"Favela" => "Favela",
			"Fazenda" => "Fazenda",
			"Feira" => "Feira",
			"Jardim" => "Jardim",
			"Ladeira" => "Ladeira",
			"Lago" => "Lago",
			"Lagoa" => "Lagoa",
			"Largo" => "Largo",
			"Loteamento" => "Loteamento",
			"Morro" => "Morro",
			"Núcleo" => "Núcleo",
			"Parque" => "Parque",
			"Passarela" => "Passarela",
			"Pátio" => "Pátio",
			"Praça" => "Praça",
			"Quadra" => "Quadra",
			"Recanto" => "Recanto",
			"Residencial" => "Residencial",
			"Rodovia" => "Rodovia",
			"Rua" => "Rua",
			"Setor" => "Setor",
			"Sítio" => "Aeroporto",
			"Travessa" => "Sítio",
			"Trecho" => "Travessa",
			"Trevo" => "Trecho",
			"Vale" => "Vale",
			"Vereda" => "Vereda",
			"Via" => "Via",
			"Viaduto" => "Viaduto",
			"Viela" => "Viela",
			"Vila" => "Vila",
			"Córrego" => "Córrego",
			"Linha" => "Linha",
			"Margem" => "Margem",
			"Passagem" => "Passagem",
			"Praia" => "Praia",
			"Superquadra" => "Superquadra",
			"Outro" => "Outro",
		),
		'tipo_feedback_pergunta' => array(
			'texto' => 'Texto',
			'nota' => 'Nota',
		),
		'meses' => array(
			'01' => 'Janeiro',
			'02' => 'Fevereiro',
			'03' => 'Março',
			'04' => 'Abril',
			'05' => 'Maio',
			'06' => 'Junho',
			'07' => 'Julho',
			'08' => 'Agosto',
			'09' => 'Setembro',
			'10' => 'Outubro',
			'11' => 'Novembro',
			'12' => 'Dezembro',
		),
		'payment_gateway' => array(
			'boletoitau' => 'Boleto',
			'mp' => 'Mercado Pago',
		),
		'payment_status' => array(
			'processando' => 'Processando',
			'aguardando' => 'Aguardando Pagamento',
			'cancelado' => 'Cancelado',
			'recusado' => 'Recusado',
			'pago' => 'Pago',
		),
	);
}
?>